/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class glovalib_wcas_WindowsConsoleAnsiSupport */

#ifndef _Included_glovalib_wcas_WindowsConsoleAnsiSupport
#define _Included_glovalib_wcas_WindowsConsoleAnsiSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     glovalib_wcas_WindowsConsoleAnsiSupport
 * Method:    TryStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_glovalib_wcas_WindowsConsoleAnsiSupport_TryStart
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
